chore: bump to rxJava3
gravitee-io/gravitee-cockpit-api pull request #117
Opened 2022-09-23 06:49 UTC by marcambier

https://github.com/gravitee-io/issues/issues/7990

2022-09-23 12:47 UTC, mariano-fernandez requested changes

2022-09-23 12:47 UTC, mariano-fernandez commented on pom.xml
> +        <gravitee-node-api.version>2.0.0-bumpRxJava3-SNAPSHOT</gravitee-node-api.version>
I guess we are waiting for the new version of `gravitee-node` to be released. But we don't have to forget to update it here

2022-10-18 12:07 UTC, ytvnr approved these changes

2022-10-18 12:10 UTC, mariano-fernandez approved these changes

2022-10-18 13:38 UTC, merged

2022-10-18 13:40 UTC, graviteeio commented
:tada: This PR is included in version 2.0.0-alpha.1 :tada:

The release is available on:
- `2.0.0-alpha.1`
- [GitHub release](https://github.com/gravitee-io/gravitee-cockpit-api/releases/tag/2.0.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2022-12-12 10:23 UTC, graviteeio commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- `2.0.0`
- [GitHub release](https://github.com/gravitee-io/gravitee-cockpit-api/releases/tag/2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: